### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by pwcberry** [benquarmby/jslintnet#3]
IE11 and the evergreen browsers (Firefox and Chrome) now support many features of ES6 such as keywords and types.

Application developers who are not required to support older browsers would like to write safe JavaScript code using these new features.

As Crockford is working on a [new version of JSLint](http://new.jslint.com/jslint.html), JSLint.NET should be updated to work with ES6.

**Comment by benquarmby** [comment]
That's a great question, and something I've been thinking about since [Crockford announced](https://plus.google.com/+DouglasCrockfordEsq/posts/aeJGSb7zheb) the JSLint rewrite in Feb.

There are a few things that are holding it back right now:
- The new JSLint is still in alpha, being actively developed and seeking feedback. A version of JSLint.NET that wrapped this new version would have to be in alpha too.
- More than half of the existing JSLint switches are gone in this new version. It would be an understatement to call that a breaking change. I imagine most if not all ES3 / ES5 programs using JSLint today would be affected. For example, anything relying on "unparam" will have to be rewritten.
- A new JSLint.NET would have to be provided as an alternative, not a replacement. So there would be two versions to maintain.
- Crockford has not released the source code for the new JSLint yet. So there is no unobfuscated version to include in projects like this one.

With all of that said, it is definitely going to happen. I'm just not sure when yet.

**Comment by benquarmby** [comment]
OK, so Crockford [just dropped](https://plus.google.com/+DouglasCrockfordEsq/posts/L5J71M2Kzu5) the beta version and made the source available. Things will start to move a bit faster now. I can see a JSLint.NET 2.0 Beta soon.

**Comment by pwcberry** [comment]
Thanks for the update! I think releasing v2 of JSLint.NET for ES6 is the right approach.

**Comment by benquarmby** [comment]
I've just posted the [2.0.0-beta5 pre-release](https://github.com/benquarmby/jslintnet/releases) that wraps JSLint ES6. Check out the [beta page](https://github.com/benquarmby/jslintnet/wiki/JSLint.NET-2.0-Beta) for some extra detail.

**Comment by benquarmby** [comment]
[Beta 6 has just been posted](https://github.com/benquarmby/jslintnet/releases), and is likely to be the last beta before a final release. I've also created an [upgrade announcement wiki page](https://github.com/benquarmby/jslintnet/wiki/Upgrade-Announcement) to get everyone ready for the breaking changes.

Douglas Crockford is still fielding some bug reports [from the community](https://plus.google.com/communities/104441363299760713736), but I expect that will settle down soon. So I think JSLint.NET 2.0 will be ready to go in a matter of weeks now.

**Comment by benquarmby** [comment]
The ES6 branch has now been merged and released.
