### ISSUE TITLE
Documentation discrepancy between 1.x and 2.x

### ISSUE THREAD

**Issue by ssg** [benquarmby/jslintnet#37]
There seems to be no way to disable "Bad property name" warnings completely in 2.x and you suggested we should downgrade to 1.x so I did that. However, documentation is for 2.x and it seems to create problems. For example `globalVariables` doesn't work for 1.x and I have no idea what the new syntax should be. Thank you for this tool but this whole adventure of trial by errors needs some attention as well.

**Comment by benquarmby** [comment]
Version 1.x was against the now very old JSLint, which had very little to no knowledge of ES2015. I would not describe it as a tenable option.

JSLint is completely unforgiving of external libraries that use bad property names (among other API problems). The fact that hoops need to be jumped to tolerate them is likely by design.

**Comment by ssg** [comment]
Makes sense. thanks!
